[package]
name = "duckfetch"
version = "0.5.2"
edition = "2024"
description = "A CLI tool for managing DuckDB installations, enabling users to easily list available versions and install specific ones."
documentation = "https://docs.rs/duckfetch"
readme = "README.md"
homepage = "https://github.com/pmassicotte/duckfetch"
repository = "https://github.com/pmassicotte/duckfetch"
license = "MIT OR Apache-2.0"
keywords = ["CLI", "DuckDB", "database", "fetch", "tool"]
categories = ["command-line-interface"]

[dependencies]
anyhow = "1.0"
clap = { version = "4.6", features = ["cargo", "color"] }
clap_complete = "4.6.5"
dirs = "6"
inquire = "0.9"
reqwest = {
  version = "0.13",
  default-features = false,
  features = ["blocking", "json", "rustls"]
}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3"
webbrowser = "1.2.1"
zip = "8"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = "z"
strip = "symbols"
lto = "fat"
panic = "abort"
codegen-units = 1

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
