[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
create-release = true
# The installers to generate for each app
installers = ["shell", "powershell"]
# The archive format to use for windows builds (defaults .zip)
windows-archive = ".zip"
# The archive format to use for non-windows builds (defaults .tar.xz)
unix-archive = ".tar.gz"
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
  # Mac
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",
  # Windows
  "x86_64-pc-windows-msvc",
  "aarch64-pc-windows-msvc",
  # Linux
  "x86_64-unknown-linux-gnu",
  # "aarch64-unknown-linux-gnu",
]
install-path = ["$XDG_BIN_HOME/", "$XDG_DATA_HOME/../bin", "~/.local/bin"]
global = "ubuntu-latest"
