name: Build Binaries

on:
  workflow_dispatch:
  push:
    tags:
      - "v*" # Only trigger when creating a tag
jobs:
  build:
    name: Build and Release Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    permissions:
      contents: write

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Rust toolchain
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: cargo

      # Build the project
      - name: Build the project
        run: cargo build --release

      # Upload the binaries as build artifacts
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-binary
          path: ${{ format('target/release/{0}', (matrix.os == 'windows-latest') && 'duckfetch.exe' || 'duckfetch') }}

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      # Checkout the code to get the tag info
      - name: Checkout code
        uses: actions/checkout@v3

      # Create a GitHub release
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/duckfetch
            target/release/duckfetch.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
