name: Test macOS Installation

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-macos:
    name: Test macOS Installation (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: x86_64
            runner: macos-latest
          - arch: arm64
            runner: macos-14 # Apple Silicon runner

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build and Install
        run: |
          cargo install --path .
          duckfetch --version

      - name: Install DuckDB using duckfetch
        env:
          DUCKFETCH_NON_INTERACTIVE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          duckfetch update
          ~/.local/bin/duckdb --version
