name: Test Windows Installation

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-windows:
    name: Test Windows Installation
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build and Install (x86_64)
        run: |
          cargo install --path .
          duckfetch --version

      - name: Install DuckDB using duckfetch
        env:
          DUCKFETCH_NON_INTERACTIVE: true
        shell: pwsh
        run: |
          duckfetch update
          & "$env:USERPROFILE\.duckdb\bin\duckdb.exe" --version
